# Generated by Django 5.1.6 on 2025-03-21 08:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Candidate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("email", models.EmailField(max_length=254, unique=True)),
                (
                    "mobile_number",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                (
                    "phone_number",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                ("location", models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="CreateEmailTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Email_Template_Id", models.CharField(max_length=100, unique=True)),
                ("Email_Template_Description", models.CharField(max_length=500)),
                ("BoActive", models.BooleanField(default=True)),
                (
                    "Header_Image_Location",
                    models.ImageField(blank=True, null=True, upload_to="headers/"),
                ),
                (
                    "Footer_Image_Location",
                    models.ImageField(blank=True, null=True, upload_to="footers/"),
                ),
                ("Email_Template_Subject", models.CharField(max_length=300)),
                ("Body_Html", models.TextField()),
                (
                    "Sender_Email_Id",
                    models.CharField(
                        choices=[
                            ("info@talentmitra.com", "info@talentmitra.com"),
                            ("info@cvmitra.com", "info@cvmitra.com"),
                            ("info@jobmitra.com", "info@jobmitra.com"),
                        ],
                        default="info@jobmitra.com",
                        max_length=255,
                    ),
                ),
                (
                    "Reply_To_Email_Id",
                    models.EmailField(blank=True, max_length=255, null=True),
                ),
                (
                    "Created_User_Id",
                    models.CharField(
                        choices=[
                            ("System Admin", "System Admin"),
                            ("Recruiter Id", "Recruiter Id"),
                        ],
                        default="System Admin",
                        max_length=50,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="EmailTag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="Resume",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("file_url", models.URLField()),
                ("extracted_data", models.JSONField(blank=True, null=True)),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="APIKey",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("key", models.CharField(editable=False, max_length=200, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CandidateEducation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("institution", models.CharField(max_length=255)),
                ("degree", models.CharField(max_length=255)),
                ("start_date", models.CharField(blank=True, max_length=50, null=True)),
                ("end_date", models.CharField(blank=True, max_length=50, null=True)),
                ("gpa", models.FloatField(blank=True, null=True)),
                (
                    "candidate",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="education",
                        to="mainapp.candidate",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CandidateExperience",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("company", models.CharField(max_length=255)),
                ("role", models.CharField(max_length=255)),
                ("start_date", models.CharField(blank=True, max_length=50, null=True)),
                ("end_date", models.CharField(blank=True, max_length=50, null=True)),
                ("responsibilities", models.TextField()),
                (
                    "candidate",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="experience",
                        to="mainapp.candidate",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CandidateSkill",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("skill_type", models.CharField(max_length=50)),
                ("skill_name", models.CharField(max_length=100)),
                (
                    "candidate",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="skills",
                        to="mainapp.candidate",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CandidateTotalExperience",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("total_years", models.IntegerField(default=0)),
                ("total_months", models.IntegerField(default=0)),
                (
                    "candidate",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="total_experience",
                        to="mainapp.candidate",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="EmailLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user_type", models.CharField(max_length=100)),
                ("email_to", models.EmailField(max_length=254)),
                ("email_cc", models.TextField(blank=True, null=True)),
                ("email_bcc", models.TextField(blank=True, null=True)),
                (
                    "reply_to_email",
                    models.EmailField(blank=True, max_length=254, null=True),
                ),
                ("email_send_date", models.DateTimeField(auto_now_add=True)),
                ("email_subject", models.CharField(max_length=300)),
                ("email_body", models.TextField()),
                (
                    "email_deliver_status",
                    models.CharField(
                        choices=[
                            ("Delivered", "Delivered"),
                            ("Failed", "Failed"),
                            ("Pending", "Pending"),
                        ],
                        default="Pending",
                        max_length=50,
                    ),
                ),
                ("email_failure_message", models.TextField(blank=True, null=True)),
                ("retry_count", models.IntegerField(default=0)),
                (
                    "ses_message_id",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "email_template",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="email_logs",
                        to="mainapp.createemailtemplate",
                    ),
                ),
            ],
        ),
    ]
