# Generated by Django 5.1.6 on 2025-03-24 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mainapp", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="resume",
            name="file_url",
            field=models.TextField(),
        ),
    ]
