# Generated by Django 5.1.6 on 2025-03-25 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mainapp", "0002_alter_resume_file_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="candidate",
            name="profile_summary",
            field=models.TextField(blank=True, null=True),
        ),
    ]
