# Generated by Django 5.1.6 on 2025-04-08 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mainapp", "0003_candidate_profile_summary"),
    ]

    operations = [
        migrations.AddField(
            model_name="resume",
            name="uploaded_by_id",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="resume",
            name="user_type",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
