# Generated by Django 5.1.6 on 2025-04-16 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mainapp", "0004_resume_uploaded_by_id_resume_user_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="resume",
            name="embedding",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
