# Generated by Django 5.1.6 on 2025-04-16 08:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("mainapp", "0005_resume_embedding"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="resume",
            name="embedding",
        ),
    ]
